dist: trusty
language: node_js
node_js:
- stable
cache:
  # cache both npm modules and Cypress binary
  directories:
  - ~/.npm
  - ~/.cache
  override:
  - npm ci
  - npm run cy:verify
notifications:
  email:
    recipients:
    - julia.z@chello.at      # change to your own address
    on_success: never        # default: change
    on_failure: always       # default: always
deploy:
  provider: heroku
  api_key:
    secure: "2e32271d-bc23-4adf-9472-d0585a86aeae"
  app: morsevue
defaults: &defaults
  script:
  - npm start -- --silent &
  - npm run cy:run -- --record --parallel --group $STAGE_NAME
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  - kill $(jobs -p) || true
